platform :ios ,'8.0'
target ‘DanTang’ do 
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Masonry', '~> 1.0.1'
	pod 'IQKeyboardManager', '~> 4.0.4'
	pod 'MJExtension', '~> 3.0.11'
	pod 'MBProgressHUD', '~> 0.9.2'
 	pod 'SVProgressHUD', '~> 2.0.3'
 	pod 'MJRefresh', '~> 3.1.10'
end

